name: Linting, testing
on:
  # Steps described below will run on this actions
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    # Use the same environment as in production
    runs-on: ubuntu-latest
    # These steps will run on actions described above
    steps:
      - uses: actions/checkout@v4

      - name: Staring Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installing node modules
        run: npm install

      - name: Linting typescript
        run: npm run lint:fix

      - name: Linting css
        run: npm run stylelint:fix

      - name: Testing
        run: npm run test
